- apt: upgrade=dist update_cache=yes

- name: Basic utils
  apt: name={{ item }} 
  with_items:
  - curl
  - emacs
  - git
  - git-core
  - git-core
  - links
  - lynx
  - mercurial
  - mosh
  - nmap
  - npm
  - whois
  - screen
  - exiv2

- name: Additional utils
  apt: name={{ item }} 
  with_items:
  - mongodb-clients

- name: Python
  apt: name={{ item }} 
  with_items:
  - cython
  - ipython
  - ipython
  - libxml2-dev
  - libxslt1-dev
  - python-boto
  - python-boto
  - python-bson
  - python-dev
  - python-matplotlib
  - python-matplotlib
  - python-numpy
  - python-pandas
  - python-pip
  - python-pip
  - python-scipy
  - python-scipy
  - python-setuptools
  - python-sklearn
  - virtualenvwrapper

- pip: name=fs
- pip: name=node

- apt: name=python-virtualenv
  when: ansible_distribution_version == '14.04'
- apt: name=virtualenv
  when: ansible_distribution_version == '15.04'
- apt: name=python-mysqldb
- apt: name=python-pymysql
  when: ansible_distribution_version == '15.04'
- apt: name=python-mysql.connector
  when: ansible_distribution_version == '14.04'

