- apt: upgrade=dist update_cache=yes

- name: Basic utils
  apt: name={{ item }} 
  with_items:
  - emacs
  - git-core
  - git
  - mosh
  - git-core
  - links
  - lynx
  - mercurial
  - nmap
  - curl
  - whois

- name: Python
  apt: name={{ item }} 
  with_items:
  - ipython
  - ipython
  - python-boto
  - python-boto
  - python-bson
  - python-matplotlib
  - python-matplotlib
  - python-numpy
  - python-pandas
  - python-pip
  - python-pip
  - python-scipy
  - python-scipy
  - python-setuptools
  - python-sklearn
  - virtualenvwrapper

- apt: name=python-virtualenv
  when: ansible_distribution_version == '14.04'
- apt: name=virtualenv
  when: ansible_distribution_version == '15.04'
- apt: name=python-mysqldb
- apt: name=python-pymysql
  when: ansible_distribution_version == '15.04'
- apt: name=python-mysql.connector
  when: ansible_distribution_version == '14.04'

- pip: name=fs
- pip: name=node
