- apt: name=xmonad
- apt: name=xmobar
- apt: name=kdm
- apt: name=meld
- apt: name=texlive-base
- apt: name=texlive-latex-extra
- apt: name=texlive-latex-recommended
- apt: name=mplayer
- apt: name=shutter
- apt: name=texlive-fonts-recommended
- apt: name=inkscape