- name: Desktop applications
  apt: name={{ item }} 
  with_items:
  - gimp
  - xcftools
  - gthumb
  - inkscape
  - kdenlive
  - meld
  - mplayer
  - mysql-workbench
  - shutter
  - xmobar
  - xmonad
  - xournal
  - xcircuit
  - youtube-dl
  - tesseract-ocr

- name: Desktop network utils
  apt: name={{ item }} 
  with_items:
  - epic4
  - gufw
  - nmap
  - openconnect
  - ufw
  - vpnc

- name: LaTeX
  apt: name={{ item }} 
  with_items:
  - texlive-base
  - texlive-fonts-extra
  - texlive-fonts-recommended
  - texlive-latex-extra
  - texlive-latex-recommended
  - texlive-publishers
  - texlive-xetex
  - pdftk

- name: edX requirements
  apt: name={{ item }} 
  with_items:
  - nfs-common
  - nfs-kernel-server

- name: fonts
  apt: name={{ item }}
  with_items:
  - xfonts-base
  - xfonts-100dpi
  - xfonts-75dpi

- name: androidstudioreqs
  apt: name={{ item }}
  with_items:
  - libc6:i386
  - libncurses5:i386
  - libstdc++6:i386
  - lib32z1
  - libbz2-1.0:i386
  - qemu-kvm
  - libvirt-bin
  - ubuntu-vm-builder
  - bridge-utils

# - include: google-drive-ocaml.yaml
- command: git config --global user.email "piotr@mitros.org"

- command: git config --global user.name "Piotr Mitros"
- command: su -c 'git config --global user.email "piotr@mitros.org"' pmitros
- command: su -c 'git config --global user.name "Piotr Mitros"' pmitros

- copy: src=scripts/virtualenvwrapper.sh dest=/tmp
- command: sh /tmp/virtualenvwrapper.sh

- apt: name=wine-stable
  when: ansible_distribution_version == '16.10'

- apt: name=wine
  when: ansible_distribution_version == '16.04'