- apt: name=xmonad
- apt: name=xmobar
- apt: name=kdm
- apt: name=meld
- apt: name=nmap
- apt: name=ufw
- apt: name=gufw
- command: git config --global user.email "piotr@mitros.org"
- command: git config --global user.name "Piotr Mitros"
