- name: Desktop applications
  apt: name={{ item }} 
  with_items:
  - xmonad
  - xmobar
  - meld
  - mplayer
  - shutter
  - inkscape
  - gimp
  - gthumb

- name: Desktop network utils
  apt: name={{ item }} 
  with_items:
  - nmap
  - ufw
  - gufw
  - openconnect

- name: LaTeX
  apt: name={{ item }} 
  with_items:
  - texlive-base
  - texlive-publishers
  - texlive-latex-extra
  - texlive-latex-recommended
  - texlive-fonts-recommended
  - texlive-fonts-extra
  - texlive-xetex

- apt: name=npm
- apt: name=epic4

- name: edX requirements
  apt: name={{ item }} 
  with_items:
  - nfs-common
  - nfs-kernel-server

# - include: google-drive-ocaml.yaml
- command: git config --global user.email "piotr@mitros.org"

- command: git config --global user.name "Piotr Mitros"
- command: su -c 'git config --global user.email "piotr@mitros.org"' pmitros
- command: su -c 'git config --global user.name "Piotr Mitros"' pmitros

- copy: src=scripts/virtualenvwrapper.sh dest=/tmp
- command: sh /tmp/virtualenvwrapper.sh